# Generated by Django 2.1 on 2018-08-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=30)),
                ('apelido', models.CharField(blank=True, max_length=30)),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('documento', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone', models.CharField(blank=True, max_length=13, null=True)),
            ],
        ),
    ]
