# Generated by Django 2.1 on 2018-08-11 00:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(blank=True, max_length=50)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 11, 0, 47, 6, 617048))),
                ('peso', models.IntegerField(blank=True)),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('ENCERRADA', 'Encerrada')], default='ATIVA', max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendas.Cliente')),
            ],
        ),
    ]
