# Generated by Django 2.1 on 2018-08-11 00:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 11, 0, 49, 17, 947412, tzinfo=utc)),
        ),
    ]
