# Generated by Django 2.1 on 2018-08-11 00:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_auto_20180811_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='date',
        ),
        migrations.AddField(
            model_name='venda',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 11, 0, 55, 28, 186995, tzinfo=utc)),
        ),
    ]
