# Generated by Django 2.1 on 2018-08-11 01:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_auto_20180810_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='cod',
        ),
        migrations.AlterField(
            model_name='venda',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 11, 1, 33, 20, 763921, tzinfo=utc)),
        ),
    ]
